CREATE TABLE "public"."feedback" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone DEFAULT now(),
  "inserted_by"     uuid,
  "source"          text                     NOT NULL,
  "organization_id" uuid                     NOT NULL,
  "identifier_id"   text                     NOT NULL,
  "metadata"        jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "feedback_identifier_id_key" UNIQUE (identifier_id),
  CONSTRAINT "feedback_inserted_by_fkey" FOREIGN KEY (inserted_by) REFERENCES auth.users(id) ON DELETE SET NULL,
  CONSTRAINT "feedback_pkey" PRIMARY KEY (id),
  CONSTRAINT "feedback_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "feedback_source_fkey" FOREIGN KEY (source) REFERENCES public.sources(key)
);

ALTER TABLE "public"."feedback"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."feedback"
  ADD COLUMN "status" public.status DEFAULT 'untriaged'::public.status;

CREATE POLICY "ALLOW INSERT FOR ANYONE" ON "public"."feedback"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Anyone can select" ON "public"."feedback"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."feedback" TO "anon", "authenticated", "postgres", "service_role";

COMMENT ON TABLE "public"."feedback" IS 'Items of feedback for an organization';
