SET local check_function_bodies = off;

CREATE EXTENSION "pg_cron";

CREATE EXTENSION "pg_net" SCHEMA "extensions";

CREATE EXTENSION "pgjwt" SCHEMA "extensions";

CREATE EXTENSION "vector" SCHEMA "extensions";

CREATE SEQUENCE "public"."teams_id_seq" AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;

CREATE TABLE "public"."feedback" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone DEFAULT now(),
  "inserted_by"     uuid,
  "source"          text                     NOT NULL,
  "organization_id" uuid                     NOT NULL,
  "identifier_id"   text                     NOT NULL,
  "metadata"        jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "feedback_identifier_id_key" UNIQUE (identifier_id),
  CONSTRAINT "feedback_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."feedback"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."members" (
  "team_id" bigint,
  "user_id" uuid
);

CREATE TABLE "public"."organizations" (
  "id"          uuid                        NOT NULL DEFAULT gen_random_uuid(),
  "created_at"  timestamp with time zone    DEFAULT now(),
  "updated_at"  timestamp without time zone DEFAULT now(),
  "inserted_by" uuid                        NOT NULL,
  "name"        text                        NOT NULL,
  CONSTRAINT "organizations_name_key" UNIQUE (name),
  CONSTRAINT "organizations_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."organizations"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sources" (
  "id"    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "label" text   NOT NULL,
  "key"   text   NOT NULL,
  CONSTRAINT "sources_key_key" UNIQUE (key),
  CONSTRAINT "sources_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sources"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."teams" (
  "id"   integer NOT NULL DEFAULT nextval('public.teams_id_seq'::regclass),
  "name" text,
  CONSTRAINT "teams_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."teams"
  ENABLE ROW LEVEL SECURITY;

ALTER SEQUENCE "public"."teams_id_seq" OWNED BY "public"."teams"."id";

CREATE TYPE "public"."source" AS ENUM (
  'internal',
  'twitter',
  'reddit',
  'email',
  'phone',
  'custom'
);

CREATE TYPE "public"."status" AS ENUM (
  'resolved',
  'review',
  'in_progress',
  'planned',
  'untriaged'
);

ALTER TABLE "public"."feedback"
  ADD COLUMN "status" public.status DEFAULT 'untriaged'::public.status;

ALTER TABLE "public"."feedback"
  ADD CONSTRAINT "feedback_inserted_by_fkey" FOREIGN KEY (inserted_by) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE "public"."members"
  ADD CONSTRAINT "members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."organizations"
  ADD CONSTRAINT "organizations_inserted_by_fkey" FOREIGN KEY (inserted_by) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."feedback"
  ADD CONSTRAINT "feedback_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."feedback"
  ADD CONSTRAINT "feedback_source_fkey" FOREIGN KEY (source) REFERENCES public.sources(key);

ALTER TABLE "public"."members"
  ADD CONSTRAINT "members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id);

CREATE POLICY "ALLOW INSERT FOR ANYONE" ON "public"."feedback"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Anyone can select" ON "public"."feedback"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Owner can select" ON "public"."organizations"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = inserted_by));

CREATE POLICY "select_organizations_policy" ON "public"."organizations"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = id));

CREATE POLICY "view_organizations_policy" ON "public"."organizations"
  FOR SELECT
  TO "authenticated"
  USING ((inserted_by = auth.uid()));

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."organizations";

COMMENT ON EXTENSION "pg_cron" IS 'Job scheduler for PostgreSQL';

COMMENT ON EXTENSION "pg_net" IS 'Async HTTP';

COMMENT ON EXTENSION "pgjwt" IS 'JSON Web Token API for Postgresql';

COMMENT ON EXTENSION "vector" IS 'vector data type and ivfflat and hnsw access methods';

COMMENT ON TABLE "public"."feedback" IS 'Items of feedback for an organization';

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."teams_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."feedback" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."members" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."organizations" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sources" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."teams" TO "anon", "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."source" TO "postgres";

GRANT USAGE ON TYPE "public"."status" TO "postgres";
